### ISSUE TITLE
Add forward slash to HTML entities

### ISSUE THREAD

**Issue by momendo** [jjenzz/jquery.ellipsis#12]
https://github.com/jjenzz/jquery.ellipsis/blob/a1c97ac6ae1e5dbbcf26adb981b0edcddbd5e6a4/jquery.ellipsis.js#L60-L61

We should add forward slash to the html entities list. Otherwise, forward slash returns 'undefined'

https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet

`'/': '&#x2F;'`

**Comment by Rub3s** [comment]
I agree, it solved the problem for me.

**Comment by clay-reed-a** [comment]
@jjenzz Can we create a PR for this? I still experience this issue.

**Comment by arlopurcell** [comment]
done
#14

**Comment by jjenzz** [comment]
Merged. Thank you @arlopurcell
